### ISSUE TITLE
Retire IE11 Support

### ISSUE THREAD

**Issue by davidjoy** [openedx/wg-frontend#3]
While it may sound like maintenance, this is about how IE 11 holds us back from a number of newer technologies in the frontend, newer syntax, HTTP/2, i18n libraries, etc.

Related Jira tickets:
1. https://openedx.atlassian.net/browse/ENT-4830
2. https://openedx.atlassian.net/browse/WS-2132

- [x] Parse Segment page view events in Enterprise MFEs to understand IE usage across customers in the past year.
- [x] Identify the correct UI component to show to IE 11 users with messaging to inform them about upgrading to a new browser (e.g., Chrome). We will use the `PageBanner` component from Paragon, specifically the "warning" variant.
- [x] Sync with #website squad on any messaging needs there, and timeline for when to show the alert / `PageBanner`.
- [x] Select a way to conditionally render a component only IE users only (e.g., library). `prospectus` (edx.org) is using Google Tag Manager.
- [x] Implement in edx.org (prospectus)
- [ ] ~Implement in Enteprise MFEs.~ (decision: no messaging needed)
- [x] Inform the Support team of this decision.
- [x] Ensure IE is removed from [supported browsers in Support Portal](https://support.edx.org/hc/en-us/articles/206211848-What-are-the-system-requirements-and-supported-browsers-on-edX-)
- [ ] Identify and remove mention of IE in technical documentation.
- [x] Announce at the next FedX meeting and FWG meetings.
- [ ] Create Discourse post to let community know of this decision.
- [ ] Get this into Open edX release notes for Nutmeg
- [ ] Remove "ie 11" from `browserslist`s throughout the platform (primarily MFEs) https://docs.google.com/spreadsheets/d/1fduFbAxIbckiwHKNCtc41ImAL_CFIl9hZcC4AjDkuvI/edit?usp=sharing
- [ ] Notify the Build-Test-Release working group.

**Comment by adamstankiewicz** [comment]
The decision has been made 😉  We have officially dropped support for Internet Explorer 11 as of today. Only 0.15% of users in the past 3 months on the B2C side of things (edx.org) used IE 11. In the Enterprise products, only 0.8% of users in the past 3 months used IE 11 (notably on the Enterprise Admin Portal).

The edx.org website implemented a banner with messaging about no longer supporting IE 11 for users viewing the site from that browser:

![image](https://user-images.githubusercontent.com/2828721/136268989-f2913138-be3c-46dc-a7f1-d4bafde0f997.png)

I updated the top-level issue description's task list to account for post-decision follow-ups around removing mentions of IE support from our support portal and documentation, to announce this decision at appropriate venues (e.g., FWG meeting), and to create a Discourse post to inform the community of this decision.

This decision is exciting because is unblocks several tech initiatives, including using CSS variables, simplifying frontend build processes, Bootstrap 5 upgrade, removing now-irrelevant polyfills, etc.

We do not plan to make any changes related to these initiatives prior to the Maple release of Open edX (the cut is tentatively ~ October 16).

**Comment by arbrandes** [comment]
We're pretty much done, here. :)
